### ISSUE TITLE
raise exception on conf file bad format

### ISSUE THREAD

**Issue by fpeterschmitt** [b3j0f/conf#1]
There is nothing indicating a bad format of a configuration file.

**Comment by Leryan** [comment]
Well, I might just give an extra bit of explanation:

By « bad format », I don't mean checking for the right values or the rights keys, I mean checking the basic syntax of the file being read by b3j0f.conf. Just as simple as that.

**Comment by b3j0f** [comment]
I added the attribute "logger" in the Configurable class.

If you set it with your own logger, you can log errors occuring with bad format of configuration files for example.

Enjoy

**Comment by Leryan** [comment]
![gtmac](http://cdn.meme.am/instances2/500x/5066049.jpg)
